---
- name: XplaRunner | Creating user
  user:
    name: xpla-ghslides
    comment: 'User for ghslides web application'

- name: XplaRunner | Directory /srv/
  file:
    path: /srv
    state: directory

- name: XplaRunner | Directory /srv/_packages
  file:
    path: /srv/_packages
    state: directory

- name: XplaRunner | Create directory for app
  file:
    path: /srv/git.{{ server_name }}
    state: directory
    mode: 0755
    owner: xpla-ghslides

- name: XplaRunner | Verify newest version
  file:
    state: absent
    path: /srv/_packages/ghslides-{{xplarunner_version}}.tar.gz
  when: xplarunner_version == 'lastSuccessfulBuild'

- name: XplaRunner | Fetching app
  command: "wget https://applejack.todr.me/job/XplaRunner/{{xplarunner_version}}/artifact/ghslides.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/ghslides_{{xplarunner_version}}.tar.gz"
  args:
    creates: /srv/_packages/ghslides_{{xplarunner_version}}.tar.gz

- name: XplaRunner | Unpacking
  unarchive:
    copy: no
    dest: "/srv/git.{{ server_name }}"
    src: "/srv/_packages/ghslides_{{xplarunner_version}}.tar.gz"

- name: Installing Modules
  command: "yarn install --production"
  environment:
    NODE_ENV: production
  args:
    chdir: "/srv/git.{{ server_name }}/github-to-slides"

- name: Installing deps
  apt:
    pkg: libssl-dev
    state: present

- name: Installing Modules
  npm:
    production: yes
    path: "/srv/git.{{ server_name }}/git-to-slides"

- name: Run On Startup
  command: "pm2 startup -u xpla-ghslides --hp /home/xpla-ghslides"
  args:
    chdir: "/srv/git.{{ server_name }}/github-to-slides"

- name: delete existing pm2 processes if running
  command: "pm2 delete xpla-ghslides"
  ignore_errors: True
  become: yes
  become_user: xpla-ghslides

- name: start pm2 process
  command: 'pm2 start --name "xpla-ghslides" index.js'
  args:
    chdir: "/srv/git.{{ server_name }}/github-to-slides"
  become: yes
  become_user: xpla-ghslides
  environment:
    NODE_ENV: "production"
    PORT: "{{ gh_server_port }}"


