export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const MODIFY_ACTIVE_TAB_CONTENT = 'MODIFY_ACTIVE_TAB_CONTENT';
export const SAVE_WORKSPACE_AS_ZIP = 'SAVE_WORKSPACE_AS_ZIP';
export const COMMIT_AND_RUN_CODE = 'COMMIT_AND_RUN_CODE';
export const COMMIT_AND_RUN_CODE_STARTED = 'COMMIT_AND_RUN_CODE_STARTED';
export const COMMIT_AND_RUN_CODE_LONG = 'COMMIT_AND_RUN_CODE_LONG';
export const COMMIT_AND_RUN_CODE_ERROR = 'COMMIT_AND_RUN_CODE_ERROR';
export const WORK_MODE_SWITCH = 'WORK_MODE_SWITCH';
export const WORK_MODE_DECK_EDIT_TOGGLE = 'WORK_MODE_DECK_EDIT_TOGGLE';
export const WORK_MODE_SAVE_SLIDE = 'WORK_MODE_SAVE_SLIDE';
export const WORK_MODE_EDIT_ANNOTATIONS = 'WORK_MODE_EDIT_ANNOTATIONS';
// Only in deck context
export const DECK_SLIDE_CHANGE = 'DECK_SLIDE_CHANGE';

// Tracking actions
export const PRESENCE_CLIENTS = 'PRESENCE_CLIENTS';
export const PRESENCE_CLIENT_SLIDE_UPDATE = 'PRESENCE_CLIENT_SLIDE_UPDATE';
