// @flow

export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB'
export const MODIFY_ACTIVE_TAB_CONTENT = 'MODIFY_ACTIVE_TAB_CONTENT'
export const SAVE_WORKSPACE_AS_ZIP = 'SAVE_WORKSPACE_AS_ZIP'
export const COMMIT_AND_RUN_CODE = 'COMMIT_AND_RUN_CODE'
export const COMMIT_AND_RUN_CODE_STARTED = 'COMMIT_AND_RUN_CODE_STARTED'
export const COMMIT_AND_RUN_CODE_LONG = 'COMMIT_AND_RUN_CODE_LONG'
export const COMMIT_AND_RUN_CODE_ERROR = 'COMMIT_AND_RUN_CODE_ERROR'
export const SLIDE_CHANGE_ANNOTATION = 'SLIDE_CHANGE_ANNOTATION'
export const WORK_MODE_SWITCH = 'WORK_MODE_SWITCH'
export const WORK_MODE_DECK_EDIT_TOGGLE = 'WORK_MODE_DECK_EDIT_TOGGLE'
export const WORK_MODE_SAVE_SLIDE = 'WORK_MODE_SAVE_SLIDE'
export const WORK_MODE_EDIT_ANNOTATIONS = 'WORK_MODE_EDIT_ANNOTATIONS'
export const WORK_MODE_EDIT_EDITOR_ANNOTATION = 'WORK_MODE_EDIT_EDITOR_ANNOTATION'

// Only in deck context
export const DECK_SLIDE_CHANGE = 'DECK_SLIDE_CHANGE'
export const DECK_PAGE_ACTIVE = 'DECK_PAGE_ACTIVE'
// Forwarded slide action
export const DECK_SLIDE_ACTION = 'DECK_SLIDE_ACTION'
// Fired by a player (middleware converts it to proper action)
export const DECK_PLAY_ACTION = 'DECK_PLAY_ACTION'

// -- Recording actions
export const RECORDING_VIEW_TOGGLE = 'RECORDING_VIEW_TOGGLE'
export const RECORDING_STATE_TOGGLE = 'RECORDING_STATE_TOGGLE'
export const RECORDING_RESET = 'RECORDING_RESET'
export const RECORDING_SET = 'RECORDING_SET'

// -- Tracking actions
export const PRESENCE_CONNECTION = 'PRESENCE_CONNECTION'
export const PRESENCE_CLIENTS = 'PRESENCE_CLIENTS'
export const PRESENCE_CLIENT_SLIDE_UPDATE = 'PRESENCE_CLIENT_SLIDE_UPDATE'
export const PRESENCE_CLIENT_ACTIVE = 'PRESENCE_CLIENT_ACTIVE'
