export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const MODIFY_ACTIVE_TAB_CONTENT = 'MODIFY_ACTIVE_TAB_CONTENT';
export const COMMIT_AND_RUN_CODE = 'COMMIT_AND_RUN_CODE';
export const COMMIT_AND_RUN_CODE_STARTED = 'COMMIT_AND_RUN_CODE_STARTED';
export const COMMIT_AND_RUN_CODE_ERROR = 'COMMIT_AND_RUN_CODE_ERROR';
// Only in deck context
export const DECK_SLIDE_CHANGE = 'DECK_SLIDE_CHANGE';
