---
- hosts: xpla-runner
  vars:
    server_name: xpla.org
    server_id: xpla
    server_port: 3030
    presence_port: 3031
    gh_server_port: 3035
  roles:
    - xpla-runner
    - xpla-github-slides

