export const STATE_NORMAL = 'state:normal'
export const STATE_RECORDING = 'state:recording'
export const STATE_PLAYING = 'state:playing'
export const VIEW_NORMAL = 'view:normal'
export const VIEW_ADMIN = 'view:recorder'
