---
- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present

- name: Nginx | Copying site
  template:
    src: nginx.config.tpl
    dest: "/etc/nginx/sites-available/{{ server_name }}"

- name: Nginx | Copying htpasswd
  copy:
    src: "htpasswd"
    dest: "/etc/nginx/{{server_name}}-htpasswd"

- name: Nginx | Copying Configuration
  template:
    src: nginx.services.tpl
    dest: "/etc/nginx/xpla/{{server_name}}.config"

- name: Nginx | Copying Configuration (presence)
  template:
    src: nginx.presence.config.tpl
    dest: "/etc/nginx/xpla/presence.{{server_name}}.config"

- name: Nginx | Copying Keys
  copy:
    src: xpla.org.crt
    dest: /etc/nginx/xpla/keys/{{server_name}}.crt

- name: Nginx | Copying Keys2
  copy:
    src: xpla.org.key
    dest: /etc/nginx/xpla/keys/{{server_name}}.key

- name: Nginx | Enabling XPla
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}"
    state: link

- service: name=nginx state=restarted
- service: name=nginx enabled=yes



