---
- name: NodeJS | Add sources
  command: curl -sL https://deb.nodesource.com/setup_6.x -o /tmp/nodesource_setup.sh
  args:
    creates: /tmp/nodesource_setup.sh

- name: NodeJS | Install
  command: bash /tmp/nodesource_setup.sh

- name: NodeJS | Install package
  apt: name=nodejs state=installed

- name: NodeJS | Tools | PM2
  npm:
    name: pm2
    global: yes

- name: NodeJS | Tools | Yarn
  npm:
    name: yarn
    global: yes

- name: Ensuring build essential
  apt: name=build-essential

