---
- name: XplaRunner | Creating user
  user:
    name: xplarunner
    comment: 'User for xplarunner web application'

- name: XplaRunner | Directory /srv/
  file:
    path: /srv
    state: directory

- name: XplaRunner | Directory /srv/_packages
  file:
    path: /srv/_packages
    state: directory

- name: XplaRunner | Create directory for app
  file:
    path: /srv/{{ server_name }}
    state: directory
    mode: 0755
    owner: xplarunner

- name: XplaRunner | Verify newest version
  file:
    state: absent
    path: /srv/_packages/xplarunner_{{xplarunner_version}}.tar.gz
  when: xplarunner_version == 'lastSuccessfulBuild'

- name: XplaRunner | Fetching app
  command: "wget https://applejack.todr.me/job/XplaRunner/{{xplarunner_version}}/artifact/xplarunner.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/xplarunner_{{xplarunner_version}}.tar.gz"
  args:
    creates: /srv/_packages/xplarunner_{{xplarunner_version}}.tar.gz

- name: XplaRunner | Unpacking
  unarchive:
    copy: no
    dest: "/srv/{{ server_name }}"
    src: "/srv/_packages/xplarunner_{{xplarunner_version}}.tar.gz"

- name: Installing Modules
  command: "yarn install --production"
  environment:
    NODE_ENV: production
  args:
    chdir: "/srv/{{ server_name }}/runner"

- name: Installing Modules
  command: "yarn install --production"
  environment:
    NODE_ENV: production
  args:
    chdir: "/srv/{{ server_name }}/presence"

- name: Run On Startup
  command: pm2 startup -u xplarunner --hp /home/xplarunner
  args:
    chdir: "/srv/{{ server_name }}/runner"

# RUNNER

- name: delete existing pm2 processes if running
  command: "pm2 delete xplarunner"
  ignore_errors: True
  become: yes
  become_user: xplarunner

- name: start pm2 process
  command: 'pm2 start --name "xplarunner" index.js'
  args:
    chdir: "/srv/{{ server_name }}/runner"
  become: yes
  become_user: xplarunner
  environment:
    NODE_ENV: "production"
    PORT: "{{ server_port }}"

# PRESENCE

- name: delete existing pm2 processes if running
  command: "pm2 delete xplapresence"
  ignore_errors: True
  become: yes
  become_user: xplarunner

- name: start pm2 process
  command: 'pm2 start --name "xplapresence" index.js'
  args:
    chdir: "/srv/{{ server_name }}/presence"
  become: yes
  become_user: xplarunner
  environment:
    NODE_ENV: "production"
    PORT: "{{ presence_port }}"
    LOGS: "/home/xplarunner/presence.log"
